name: Use Secrets
on:
  push:
    paths:
      - ".github/workflows/use-secrets.yml"

jobs:
  check-secret:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Grade use-secrets activity
        id: check-secrets
        uses: ./.github/actions/check-secrets-action
        with:
          secrets-context: ${{ toJSON(secrets) }}
      - name: Secret action
        with: # Set the secret as an input
          super_secret: ${{ secrets.SuperSecret }}
        env: # Or as an environment variable
          super_secret: ${{ secrets.SuperSecret }}
